#!/bin/sh
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
echo "Running shell script"
while read LINE; do
   echo ${LINE} + "pizda" 
   ls
done